export const CONVERT = 'CONVERT';
export const CONVERT_START = 'CONVERT_START';
export const CONVERT_SUCCESS = 'CONVERT_SUCCESS';
export const CONVERT_FAIL = 'CONVERT_FAIL';

export const SHOW_HISTORICAL_RATES = 'SHOW_HISTORICAL_RATES';
export const HISTORICAL_RATES_START = 'HISTORICAL_RATES_START';
export const HISTORICAL_RATES_SUCCESS = 'HISTORICAL_RATES_SUCCESS';
export const HISTORICAL_RATES_FAIL = 'HISTORICAL_RATES_FAIL';
