export const CONVERT = 'CONVERT';
export const CONVERT_START = 'CONVERT_START';
export const CONVERT_SUCCESS = 'CONVERT_SUCCESS';
export const CONVERT_FAIL = 'CONVERT_FAIL';

export const SHOW_HISTORICAL_RATES = 'SHOW_HISTORICAL_RATES';
export const TIME_CHANGES_START = 'TIME_CHANGES_START';
export const TIME_CHANGES_SUCCESS = 'TIME_CHANGES_SUCCESS';
export const TIME_CHANGES_FAIL = 'TIME_CHANGES_FAIL';
